### PR TITLE
Use mandrill to send transactional emails from info@pmg.org.za

### PR DESCRIPTION
**Pull request by longhotsummer**
New credentials are in google drive.

### CODE REVIEW

**Comment by petrus-jvrensburg** [comment]
I'm trying this out on dev, but I'm getting: 

```
Traceback (most recent call last):
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_security/decorators.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_security/views.py", line 119, in register
    user = register_user(**form.to_dict())
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_security/registerable.py", line 41, in register_user
    user=user, confirmation_link=confirmation_link)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_security/utils.py", line 339, in send_mail
    mail.send(msg)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 781, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 787, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 392, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 148, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 310, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by longhotsummer** [comment]
I've changed the port number back to 465 to use SSL. Try now?

**Comment by petrus-jvrensburg** [comment]
Authentication fails. But I'm using the password from the google doc.

```
2015-01-20 08:53:08,543 9369   werkzeug     INFO     127.0.0.1 - - [20/Jan/2015 08:53:08] "POST /security/register HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_security/decorators.py", line 235, in wrapper
    return f(*args, **kwargs)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_security/views.py", line 119, in register
    user = register_user(**form.to_dict())
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_security/registerable.py", line 41, in register_user
    user=user, confirmation_link=confirmation_link)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_security/utils.py", line 339, in send_mail
    mail.send(msg)
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/petrus/Desktop/code4sa/pmg-cms/env/lib/python2.7/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 615, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (435, '4.7.8 Error: authentication failed:')
```

**Comment by petrus-jvrensburg** [comment]
That's working, thanks. The only change I'm seeing is that the email confirmation links now go through mandrill's server first, e.g. `http://mandrillapp.com/track/click/...`, which is a bit weird for things like email confirmation links. But they still work.

**Comment by longhotsummer** [comment]
Thats for click tracking, everything should still just work. We can disable that, but I think it's useful to keep it.

**Comment by petrus-jvrensburg** [comment]
Cool. It's working, so I'm happy ;)

**Pull request merged**
