### PR TITLE
Viewport, description and keyword metatags

### PR DESCRIPTION
**Pull request by j-norwood-young**

### CODE REVIEW

**Comment by longhotsummer** [comment]
Nice. I'm going to hold off on merging this for now because with the new viewport setting, it looks really poor on mobile because the header doesn't collapse at all.

**Comment by j-norwood-young** [comment]
I've removed the viewport tag, wanted to keep the other meta tags in

**Comment by j-norwood-young** [comment]
I'm not getting a menu collapse with or without the tag

**Comment by longhotsummer** [comment]
> I'm not getting a menu collapse with or without the tag

Yup, that's the problem. That needs to be fixed before we enable the mobile-friendly viewport.

**Comment by longhotsummer** [comment]
This has been done outside of this pull request.

**Pull request closed without merging**
