### PR TITLE
Add new API endpoint, meetings-by-member

### PR DESCRIPTION
**Pull request by xybrnet**
@longhotsummer 

API endpoint for attendance per meeting, by member.

### CODE REVIEW

**Comment by longhotsummer** [comment]
@xybrnet can you give a quick example of the output of the API, and why the existing APIs don't work? Is this for all MPs, over all time?

**Comment by xybrnet** [comment]
@longhotsummer 

`{
  "member":{
    "party_name":"DA",
    "pa_url":"http://www.pa.org.za/person/david-john-maynier/",
    "party_id":2,
    "id":2,
    "name":"Maynier,` Mr D"},
  "meetings":[
    {"date":"2017-01-31","attendance":"A"},
    {"date":"2017-01-24","attendance":"P"},
    {"date":"2017-01-25","attendance":"P"}]}
`

We need the date for each meeting, so that we can determine the position of the member on the meeting date. The summary endpoint, only give us aggregates for number of meetings present, absent, arrived late etc. for each member.

It does get all the attendance records, for all time. I used the same query that existed for the summary API to get the members. But not all the members end up being served over the API.

**Comment by longhotsummer** [comment]
Makes sense, thanks. Can you include the meeting ID in the attendance detail dict? That gives a useful foreign key. 

Greg
--
(iPhone)

**Comment by xybrnet** [comment]
Cool, I thought that may be useful too.

**Comment by longhotsummer** [comment]
LGTM

**Pull request merged**
